routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'web'], function () {

    Route::group([
        'prefix' => 'admin',
        //'middleware' => ['ability:s2s.*,view_module,true']
        //'middleware' => ['auth', 'admin']
    ], function () {
            Auth::routes();    
            
            Route::group([
                'prefix' => '',
                'middleware' => ['auth']
            ], function() {
                    Route::get('home', 'AdminController@home')->name('admin.home');
                    Route::resource('artists', 'ActorController', [
                        'parameters' => 'singular'
                    ]);

                    Route::resource('images', 'ImageController', [
                        'parameters' => 'singular',
                        'except' => ['index','edit','store','update','create'],
                    ]);

                    Route::resource('contact', 'ContactController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                    Route::resource('register', 'RegisterController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                    Route::get('archived', 'WhatsUpController@archived')->name('whats-up.archived');
                    Route::resource('whats-up', 'WhatsUpController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('inquiry', 'InquiryController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                   Route::resource('video', 'VideoController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('whats-on', 'WhatsOnController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('skill', 'SkillController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('creatives', 'CreativeController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::get('whats-in/{whats_in}/tags', 'WhatsInController@tags')->name('whats-in.tags');
                    Route::resource('whats-in', 'WhatsInController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('category', 'CategoryController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('writer', 'WriterController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);
                } 
            );
        }
    );

    Route::group([
        'prefix'     => '',
    ], function() {

        Route::get('', 'WebsiteController@index')->name('web.index');
        Route::get('index', 'WebsiteController@index')->name('web.index');
        Route::get('home', 'WebsiteController@home')->name('web.home');
        
        Route::post('artist/search', 'WebActorController@search')->name('web.artist.search');
        Route::resource('artist', 'WebActorController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.artist.index',
                'show' => 'web.artist.show',
            ]
        ]);
       
       
        Route::post('creative/search', 'WebCreativeController@search')->name('web.creative.search');
        Route::resource('creative', 'WebCreativeController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.creative.index',
                'show' => 'web.creative.show',
            ]
        ]);
    
        Route::get('whats-up/disclaimer', 'WebWhatsUpController@disclaimer')->name('web.whats-up.disclaimer');
        Route::resource('whats-up', 'WebWhatsUpController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-up.index',
                'show' => 'web.whats-up.show',
            ]
        ]);

        Route::resource('whats-on', 'WebWhatsOnController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-on.index',
                'show' => 'web.whats-on.show',
            ]
        ]);

        Route::post('whats-in/search', 'WebWhatsInController@search')->name('web.whats-in.search');
        Route::resource('whats-in', 'WebWhatsInController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-in.index',
                'show' => 'web.whats-in.show',
            ]
        ]);

        Route::resource('contact', 'WebContactController', [
            'parameters' => 'singular',
            'except' => ['edit','show','update','create','destroy'],
            'names' => [
                'index' => 'web.contact.index',
                'store' => 'web.contact.store',
            ]
        ]);
        
        Route::resource('register', 'WebRegisterController', [
            'parameters' => 'singular',
            'except' => ['edit','show','update','create','destroy'],
            'names' => [
                'index' => 'web.register.index',
                'store' => 'web.register.store',
            ]
            
        ]);

        Route::post('actor-inquire','WebsiteController@actorInquire')->name('web.actor-inquire');
        Route::post('creative-inquire','WebsiteController@creativeInquire')->name('web.creative-inquire');
    });
    
});

app/Actor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Actor extends Model
{
    public function Image(){
        return $this->hasMany('App\Image');
    }

    public function ActorSkill(){
        return $this->hasMany('App\ActorSkill');
    }
}

app/Http/Controllers/ActorController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Actor;
use App\ActorSkill;
use App\Image;
use App\Skill;
use Yajra\Datatables\Datatables;
use Illuminate\Http\UploadedFile;
use Carbon\Carbon;

class ActorController extends Controller
{
    /*
    * display listing of the resource
    *
    *
    */
    public function index(Request $request)
	{
		if ($request->ajax()) {
			$actors = Actor::all();
			return Datatables::of($actors)->make(true);
		}

		return view('admin.actors.index');
    }
    
    /*
    *  open the form to edit the specified resource
    *
    *
    */
    public function edit($id){
        $actor = Actor::where('id','=', $id)->get();
        $images = Image::where('actor_id','=', $id)->where('group','=', 'actor')->get();
        $skills = Skill::where('group','=', 'actor')->orderBy('name')->pluck('name','id');
        $actorSkills = ActorSkill::where('actor_id','=', $id)->pluck('skill_id');
        //return view('admin.actors.edit', array('actor' => $actor, 'images' => $images, $skills => 'skills'));
        return view('admin.actors.edit', compact('actor', 'images', 'skills', 'actorSkills') );
    }

    /*
    *  Update the specified resource
    *
    *
    */
    public function update(Request $request){
        $input = $request->all();
		$id = $input['id'];

        $this->validate($request, [
            'name' => 'required',
            'age' => 'required',
            'gender' => 'required',
            'email' => 'required',
            'contact' => 'required',
            'skills' => 'required',  
            'is_active' => 'required'
        ]);
        
        $path = 'public/images/actors/';
        $allowedfileExtension=['jpg','png'];
        
        if($request->hasFile('thumb')){

            $file = $request->file('thumb');
            $filename = md5_file($file->getRealPath() );
            $extension = $file->guessExtension();
            $file = $request->file('thumb')->storeAs($path, $filename.'.'.$extension);

            $actordata = [
                'name' => $input['name'],
                'first_name' => $input['first_name'],
                'last_name' => $input['last_name'],
                'contact' => $input['contact'],
                'age' => $input['age'],
                'gender' =>$input['gender'],
                'height' => $input['height'],
                'vital' => $input['vital'],
                'manager' => $input['manager'],
                'email' => $input['email'],
                'online_profile' => $input['online_profile'],
                'works' => $input['works'],
                'thumb_image' => $filename.'.'.$extension,
                'is_active' => $input['is_active'],
                'updated_at' => Carbon::now()
            ];

        } else{
            $actordata = [
                'name' => $input['name'],
                'first_name' => $input['first_name'],
                'last_name' => $input['last_name'],
                'contact' => $input['contact'],
                'age' => $input['age'],
                'gender' =>$input['gender'],
                'height' => $input['height'],
                'vital' => $input['vital'],
                'manager' => $input['manager'],
                'email' => $input['email'],
                'online_profile' => $input['online_profile'],
                'works' => $input['works'],
                'is_active' => $input['is_active'],
                'updated_at' => Carbon::now()
            ];
        }
		
        Actor::where('id', '=', $id)->update($actordata);
        
        if($request->hasFile('photos')){
            
            $photos = $request->file('photos');
            foreach ($photos as $photo) {
                $photoname = md5_file($photo->getRealPath() );
                $ext = $photo->guessExtension();
                $file = $photo->storeAs($path, $photoname.'.'.$ext);

                $data = [
                    'actor_id' => $id,
                    'file_name' => $photoname.'.'.$ext,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'group' => 'actor',
                ];
    
                Image::insert($data);
            }
        }

        if($request->has('skills')){
            $skills = $request->input('skills');
            
            // sanitize skills. remove all before insert
            ActorSkill::where('actor_id','=', $id)->delete();

            foreach($skills as $skill){
                $actorSkill = [
                    'actor_id' => $id,
                    'skill_id' => $skill,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now()
                ];

                ActorSkill::insert($actorSkill);
            }
        }
	
		return redirect()->route('artists.index');
    }

    /*
    *  open the form to create new resource
    *
    *
    */
    public function create(){
        $skills = Skill::where('group','=', 'actor')->orderBy('name')->pluck('name','id');
        return view('admin.actors.create', compact('skills') );
    }

    /*
    *  store the newly created resource
    *
    *
    */
    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required',
            'age' => 'required',
            'gender' => 'required',
            'email' => 'required',
            'contact' => 'required',
            'thumb' => 'required',  // 'required|mimes:png,gif,jpeg,txt,pdf,doc'
            'skills' => 'required',
            'photos' => 'required',    
            'is_active' => 'required'
        ]);
        
        $path = 'public/images/actors/';
        $id = $request->input('id');
 
        $allowedfileExtension=['jpg','png'];
        $file = $request->file('thumb');
        $photos = $request->file('photos');
        
        $filename = md5_file($file->getRealPath() );
        $extension = $file->guessExtension();
        $file = $request->file('thumb')->storeAs($path, $filename.'.'.$extension);
         
        $actor_id = Actor::insertGetId([
            'name' => $request->input('name'),
            'first_name' => $request->input('first_name'),
            'last_name' => $request->input('last_name'),
            'contact' => $request->input('contact'),
            'age' => $request->input('age'),
            'gender' => $request->input('gender'),
            'height' => $request->input('height'),
            'vital' => $request->input('vital'),
            'manager' => $request->input('manager'),
            'email' => $request->input('email'),
            'online_profile' => $request->input('online_profile'),
            'works' => $request->input('works'),
            'thumb_image' => $filename.'.'.$extension,
            'is_active' =>  $request->input('is_active'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        foreach ($photos as $photo) {
            $photoname = md5_file($photo->getRealPath() );
            $ext = $photo->guessExtension();
            $file = $photo->storeAs($path, $photoname.'.'.$ext);

            $data = [
                'actor_id' => $actor_id,
                'file_name' => $photoname.'.'.$ext,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'group' => 'actor',
            ];

            Image::insert($data);
        }

        if($request->has('skills')){
            $skills = $request->input('skills');
            
            foreach($skills as $skill){
                $actorSkill = [
                    'actor_id' => $actor_id,
                    'skill_id' => $skill,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now()
                ];

                ActorSkill::insert($actorSkill);
            }
        }
	
		return redirect()->route('artists.index');
    }

    /*
    *  delete the selected resource
    *
    *
    */
    public function destroy($id){
        Actor::where('id','=', $id)->delete();
        return response()->json([
            "success" => "true",
            "message" => "Artist has been deleted.",
        ]);
    }
}

resources/views/admin/actors/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Artist')

@section('content_header')
	<h1>Filcaspro<small> Update Artist Information</small></h1>
@endsection

@section('css')
<!-- Froala Editor -->        
	
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_editor.min.css')}}">
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_style.min.css')}}">

  <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

  <link href="{{ asset('css/billboard.css') }}" rel="stylesheet">
@endsection

@section('content')
	<div class="box box-default">
		<div class="box-body">
            <!-- Images used to open the lightbox -->
            <div class="row image-container" style="text-align:center">
                @foreach($images as $image)
                    <div class="column image-{{$image->id}}">
                        <!-- <img  src="{{asset('/storage/images/actors/'. $image->file_name )}}" width="170" onclick="openModal();currentSlide({{$loop->iteration}})" class="hover-shadow"> -->
                        <span class="glyphicon glyphicon-remove icon-remove delete-btn" data-id="{{$image->id}}"></span>
                        <img  src="{{asset('/storage/images/actors/'. $image->file_name )}}" class="img-thumbnail img-responsive edit-image">
                    </div>
                @endforeach
            </div>
			<div class="row">
				<div class="col-md-12">
                   
                    @include('layouts/error_box')
                    {{Form::open(array('route' => array('artists.update', $actor[0]->id), 'method' => 'PUT', 'class' =>'form-horizontal', 'files' => true))}}
                    {{ csrf_field() }}
                    {{ Form::hidden('id', $actor[0]->id) }} 
                    <table class="table table-striped table-bordered table-hover table-sm datatable mdl-data-table dataTable" role="grid" style="width: 80%;">
							<tbody>
                            <tr>
                                <td>Name:</td>
                                <td>{{ Form::text('name', $actor[0]->name ,array('class' => 'form-control','placeholder' => 'Enter artist name')) }}</td>
                            </tr>
                            <tr>
                                <td>First name::</td>
                                <td>{{ Form::text('first_name', $actor[0]->first_name ,array('class' => 'form-control','placeholder' => 'Enter artist first name')) }}</td>
                            </tr>
                            <tr>
                                <td>Last Name:</td>
                                <td>{{ Form::text('last_name', $actor[0]->last_name ,array('class' => 'form-control','placeholder' => 'Enter artist last name')) }}</td>
                            </tr>
                            <tr>
                                <td>Contact:</td>
                                <td>{{ Form::text('contact', $actor[0]->contact ,array('class' => 'form-control','placeholder' => 'Enter artist contact')) }}</td>
                            </tr>
                            <tr>
                                <td>Age:</td>
                                <td>{{ Form::number('age', $actor[0]->age ,array('class' => 'form-control','placeholder' => 'Enter artist age')) }}</td>
                            </tr>
                            <tr>
                                <td>Gender:</td>
                                <td>{{Form::select('gender', array('' => '-----', 'male' => 'Male', 'female' => 'Female'),  $actor[0]->gender,['class' => 'form-control'])}}</td>
                            </tr>
                            <tr>
                                <td>Height:</td>
                                <td>{{ Form::text('height', $actor[0]->height ,array('class' => 'form-control','placeholder' => 'Enter artist height')) }}</td>
                            </tr>
                            <tr>
                                <td>Vital:</td>
                                <td>{{ Form::text('vital', $actor[0]->vital ,array('class' => 'form-control','placeholder' => 'Enter artist vital stats')) }}</td>
                            </tr>
                            <tr>
                                <td>Manager:</td>
                                <td>{{ Form::text('manager', $actor[0]->manager ,array('class' => 'form-control','placeholder' => 'Enter artist manager')) }}</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>{{ Form::text('email', $actor[0]->email ,array('class' => 'form-control','placeholder' => 'Enter artist email')) }}</td>
                            </tr>
                            <tr>
                                <td>Online Profile:</td>
                                <td>{{ Form::text('online_profile', $actor[0]->online_profile ,array('class' => 'form-control','placeholder' => 'Enter artist online profile')) }}</td>
                            </tr>
                            <tr>
                                <td>Works:</td>
                                <td>{{ Form::textarea('works', $actor[0]->works ,array('class' => 'form-control','id' => 'froala-editor', 'placeholder' => 'Enter artist works')) }}</td>
                            </tr>
                            <tr>
                                <td>Skills:</td>
                                <td>{{Form::select('skills[]', $skills , $actorSkills ,['class' => 'form-control select2', 'multiple' => 'multiple'])}}</td>
                            </tr>
                            <tr>
                                <td>Is Active(?):</td>
                                <td>{{Form::select('is_active', array( '' => '-----', 1 => 'Yes', 0 => 'No'),  $actor[0]->is_active,['class' => 'form-control'])}}</td>
                            </tr>
                            <tr>
                                <td>Thumb Image:</td>
                                <td> {{ Form::file('thumb') }}</td>
                            </tr>
                            <tr>
                                <td>Profile Images:</td>
                                <td> <input type="file" name="photos[]" multiple /></td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>       
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="btn-submit-container">
                    <button type="submit" class="btn btn-primary" placeholder="Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        &nbsp;
                        <a href="{{ route('artists.index') }}" title="Cancel" class="btn btn-primary btn cancel_Btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')

<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
<script src="{{ asset('js/helpers.js') }}"></script>
<script src="{{ asset('js/ajax-interceptor.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/froala/js/froala_editor.min.js')}}"></script>
<script type="text/javascript">
				
    $(function() {
        $('textarea#froala-editor').froalaEditor({
            iframe: true,
        })
    });

    $(document).ready(function() {

        $('.select2').select2().find(':selected');;

        /**
        * Delete the record.
        */
        $(document).on("click", ".delete-btn", function () {
            var self = this;
            var id = $(this).attr('data-id');
            var url = '{{ route('images.destroy', ':id') }}'.replace(':id', id);
            console.log(url);
            console.log(id);

            dhtmlx.confirm({
                title:"Confirm Deletion",
                type:"confirm-warning",
                text:"Do you really want to delete this image?",
                callback: function (res) {

                    if(!res) {
                        return;
                    }
            
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        success: function (response) {

                            dhtmlx.alert({
                                title: 'Image Deleted',
                                text: 'The image has been successfully deleted',
                                callback: function () {
                                    $('.image-' +id).remove();
                                }
                            });

                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
                }
            });
        });
    });
        
        
</script>
@endsection

resources/views/admin/actors/index.blade.php
@extends('adminlte::page')

@section('title', 'Filcaspro')

@section('content_header')

	<h1>Filcaspro<small> Artist Administration</small></h1>

@endsection

@section('css')
    <link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')
{{ csrf_field() }}
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					@include('layouts/error_box')
					
						<a href="{{ route('artists.create') }}" title="Add new Artist" class="btn btn-primary btn-xs">
							<i class="glyphicon glyphicon-plus"></i> Add new Artist
						</a>
						<br/><br/>
					
					<div class="table-responsive">
					<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
								<th>Name</th>
								<th>Gender</th>
								<th>Management</th>   
								<th>Contact</th>
								<th>Email</th>
								<th>Active (?)</th> 
								<th></th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
					
					</div>
				</div>
			</div>
		</div>
@endsection

@section('js')
	
	<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
    <script src="{{ asset('js/helpers.js') }}"></script>
    <script src="{{ asset('js/ajax-interceptor.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {

			var dataTable = $('#dataTable').DataTable({
				processing: true,
				serverSide: true,
				deferRender: true,
				ajax: '{{ route("artists.index") }}',
				columnDefs: [
					{
						'targets': 0,
						'data': 'name',
						'name': 'name',
					},
					{
						'targets': 1,
						'data': 'gender',
						'name': 'gender',
					},
					{
						'targets': 2,
						'data': 'manager',
						'name': 'manager',
					},
					{
						'targets': 3,
						'data': 'contact',
						'name': 'contact',
					
					},
					{
						'targets': 4,
						'data': 'email',
						'name': 'email',
						
					},
					{
						'targets': 5,
						'data': 'is_active',
						'name': 'is_active',
						 mRender: function ( data, type, row ) {
							if(data == 0){
								return data = 'No';
							}else if(data == 1){
								return data = 'Yes';
							}else {
								
							}
						}
					},
					{
						'targets': 6,
						'searchable': false,
						'sortable': false,
						'render': function (data, type, row) {
							return [
								'<a href="artists/' + row['id'] + '/edit" title="Edit" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i> Edit</a>' + " " +
								'<button data-id="' + row.id + '" type="button" title="Delete" class="btn btn-danger btn-xs delete-btn"><i class="fa fa-trash"></i> Delete</button>'
							];
						},
					},
				]
			});

			/**
			* Delete the record.
			*/
			$(document).on("click", ".delete-btn", function () {
				var self = this;
				var id = $(this).attr('data-id');
				var url = '{{ route('artists.destroy', ':id') }}'.replace(':id', id);
				console.log(url);
				console.log(id);
				
				dhtmlx.confirm({
					title:"Confirm Deletion",
					type:"confirm-warning",
					text:"Do you really want to delete this record?",
					callback: function (res) {

						if(!res) {
							return;
						}
				
						$.ajax({
							type: "DELETE",
							url: url,
							data: { _token: '{{csrf_token()}}' },
							success: function (response) {

								dhtmlx.alert({
									title: 'Record Deleted',
									text: 'The has been successfully deleted',
									callback: function () {
										dataTable.draw();
									}
								});

							},
							error: function (err) {
								
							}
						});
					}
				});
			});
		});
	</script>
@endsection