routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'web'], function () {

    Route::group([
        'prefix' => 'admin',
        //'middleware' => ['ability:s2s.*,view_module,true']
        //'middleware' => ['auth', 'admin']
    ], function () {
            Auth::routes();    
            
            Route::group([
                'prefix' => '',
                'middleware' => ['auth']
            ], function() {
                    Route::get('home', 'AdminController@home')->name('admin.home');
                    Route::resource('artists', 'ActorController', [
                        'parameters' => 'singular'
                    ]);

                    Route::resource('images', 'ImageController', [
                        'parameters' => 'singular',
                        'except' => ['index','edit','store','update','create'],
                    ]);

                    Route::resource('contact', 'ContactController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                    Route::resource('register', 'RegisterController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                    Route::get('archived', 'WhatsUpController@archived')->name('whats-up.archived');
                    Route::resource('whats-up', 'WhatsUpController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('inquiry', 'InquiryController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                   Route::resource('video', 'VideoController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('whats-on', 'WhatsOnController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('skill', 'SkillController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('creatives', 'CreativeController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::get('whats-in/{whats_in}/tags', 'WhatsInController@tags')->name('whats-in.tags');
                    Route::resource('whats-in', 'WhatsInController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('category', 'CategoryController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('writer', 'WriterController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);
                } 
            );
        }
    );

    Route::group([
        'prefix'     => '',
    ], function() {

        Route::get('', 'WebsiteController@index')->name('web.index');
        Route::get('index', 'WebsiteController@index')->name('web.index');
        Route::get('home', 'WebsiteController@home')->name('web.home');
        
        Route::post('artist/search', 'WebActorController@search')->name('web.artist.search');
        Route::resource('artist', 'WebActorController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.artist.index',
                'show' => 'web.artist.show',
            ]
        ]);
       
       
        Route::post('creative/search', 'WebCreativeController@search')->name('web.creative.search');
        Route::resource('creative', 'WebCreativeController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.creative.index',
                'show' => 'web.creative.show',
            ]
        ]);
    
        Route::get('whats-up/disclaimer', 'WebWhatsUpController@disclaimer')->name('web.whats-up.disclaimer');
        Route::resource('whats-up', 'WebWhatsUpController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-up.index',
                'show' => 'web.whats-up.show',
            ]
        ]);

        Route::resource('whats-on', 'WebWhatsOnController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-on.index',
                'show' => 'web.whats-on.show',
            ]
        ]);

        Route::post('whats-in/search', 'WebWhatsInController@search')->name('web.whats-in.search');
        Route::resource('whats-in', 'WebWhatsInController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-in.index',
                'show' => 'web.whats-in.show',
            ]
        ]);

        Route::resource('contact', 'WebContactController', [
            'parameters' => 'singular',
            'except' => ['edit','show','update','create','destroy'],
            'names' => [
                'index' => 'web.contact.index',
                'store' => 'web.contact.store',
            ]
        ]);
        
        Route::resource('register', 'WebRegisterController', [
            'parameters' => 'singular',
            'except' => ['edit','show','update','create','destroy'],
            'names' => [
                'index' => 'web.register.index',
                'store' => 'web.register.store',
            ]
            
        ]);

        Route::post('actor-inquire','WebsiteController@actorInquire')->name('web.actor-inquire');
        Route::post('creative-inquire','WebsiteController@creativeInquire')->name('web.creative-inquire');
    });
    
});

app/WhatsOn.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WhatsOn extends Model
{
    protected $table = 'whats_on';
}

app/Http/Controllers/WhatsOnController.php
<?php

namespace App\Http\Controllers;
use App\WhatsOn;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Carbon\Carbon;

class WhatsOnController extends Controller
{
    /*
    * display listing of the resource
    *
    *
    */
    public function index(Request $request)
	{
		if ($request->ajax()) {
            $whatson = WhatsOn::all();
			return Datatables::of($whatson)->make(true);
        }

		return view('admin.whats-on.index');
    }

     /*
    *  open the form to edit the specified resource
    *
    *
    */
    public function edit($id){
        $whatson = WhatsOn::find($id);
        return view('admin.whats-on.edit', compact('whatson') );
        // return $whatsup;
    }

    /*
    *  Update the specified resource
    *
    *
    */
    public function update(Request $request){
        
		$this->validate($request, [
            'title' => 'required',
            'venue' => 'required', 
            'date_from' => 'required',    
            'date_to' => 'required',
            'is_active' => 'required'
        ]);

        $id = $request->input('id');
 
        $data = [
            'title' => $request->input('title'),
            'venue' => $request->input('venue'), 
            'url' => $request->input('url'), 
            'date_from' => date('Y-m-d H:i:s', strtotime($request->input('date_from'))),
            'date_to' => date('Y-m-d H:i:s', strtotime($request->input('date_to'))),
            'is_active' => $request->input('is_active'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ];
        
        WhatsOn::where('id', '=', $id)->update($data);
	
		return redirect()->route('whats-on.index');
    }

    /*
    *  open the form to create new resource
    *
    *
    */
    public function create(){
        return view('admin.whats-on.create');
    }

    /*
    *  store the newly created resource
    *
    *
    */
    public function store(Request $request){
        
        $this->validate($request, [
            'title' => 'required',
            'venue' => 'required', 
            'date_from' => 'required',    
            'date_to' => 'required',
            'is_active' => 'required'
        ]);
 
        $data = [
            'title' => $request->input('title'),
            'venue' => $request->input('venue'), 
            'url' => $request->input('url'), 
            'date_from' => date('Y-m-d H:i:s', strtotime($request->input('date_from'))),
            'date_to' => date('Y-m-d H:i:s', strtotime($request->input('date_to'))),
            'is_active' => $request->input('is_active'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ];
        
        WhatsOn::insert($data);
	
        return redirect()->route('whats-on.index');
    }

     /*
    *  delete the selected resource
    *
    *
    */
    public function destroy($id){
        WhatsOn::where('id','=', $id)->delete();
        return response()->json([
            "success" => "true",
            "message" => "Event has been deleted.",
        ]);
    }
}

resources/views/admin/whats-on/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Article')

@section('content_header')
	<h1>Filcaspro<small> Create What's On Article</small></h1>
@endsection

@section('css')
<!-- Froala Editor -->

  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_editor.min.css')}}">
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_style.min.css')}}">

  <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

  <link href="{{ asset('css/billboard.css') }}" rel="stylesheet">
@endsection

@section('content')
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-md-12">

                    @include('layouts/error_box')
                    {{Form::open(array('route' => array('whats-on.store'), 'method' => 'POST', 'class' =>'form-horizontal', 'files' => true))}}
                    {{ csrf_field() }}
                    <table class="table table-striped table-bordered table-hover table-sm datatable mdl-data-table dataTable" role="grid" style="width: 80%;">
							<tbody>
                            <tr>
                                <td>Title:</td>
                                <td>{{ Form::text('title', null ,array('class' => 'form-control','placeholder' => 'Enter Event Title')) }}</td>
                            </tr>
                            <tr>
                                <td>Venue:</td>
                                <td>{{ Form::text('venue', null ,array('class' => 'form-control','placeholder' => 'Enter Event Venue')) }}</td>
                            </tr>
                            <tr>
                                <td>URL:</td>
                                <td>{{ Form::text('url', null ,array('class' => 'form-control','placeholder' => 'Enter Event URL')) }}</td>
                            </tr>
                            <tr>
                                <td>Date From:</td>
                                <td>

                                        <div class='input-group date'>
                                            <input type='text' class="form-control"  name="date_from" id='datetimepicker_from' />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>

                                </td>
                            </tr>
                            <tr>
                                <td>Date To:</td>
                                <td>

                                        <div class='input-group date'>
                                            <input type='text' class="form-control"  name="date_to" id='datetimepicker_to' />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>

                                </td>
                            </tr>
                            <tr>
                                <td>Active (?):</td>
                                <td>{{Form::select('is_active', array( '' => '-----', 1 => 'Yes', 0 => 'No'), null ,['class' => 'form-control'])}}</td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="btn-submit-container">
                    <button type="submit" class="btn btn-primary" placeholder="Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        &nbsp;
                        <a href="{{ route('whats-on.index') }}" title="Cancel" class="btn btn-primary btn cancel_Btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')
<script src="{{ asset('vendor/bootstrap-datetimepicker/moment.js') }}"></script>
<script src="{{ asset('vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js') }}"></script>
<script type="text/javascript">
		 $(document).ready(function(){
            $('#datetimepicker_from').datetimepicker({ format: 'LLL'});
            $('#datetimepicker_to').datetimepicker({ format: 'LLL'});
        });
</script>
@endsection

resources/views/admin/whats-on/edit.blade.php
@extends('adminlte::page')

@section('title', 'Filcaspro')

@section('content_header')
	<h1>Filcaspro<small>Edit What's On Article</small></h1>
@endsection

@section('css')
<!-- Froala Editor -->        
	
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_editor.min.css')}}">
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_style.min.css')}}">

  <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

  <link href="{{ asset('css/billboard.css') }}" rel="stylesheet">
@endsection

@section('content')
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-md-12">
                   
                    @include('layouts/error_box')
                    {{Form::open(array('route' => array('whats-on.update', $whatson->id), 'method' => 'PUT', 'class' =>'form-horizontal', 'files' => true))}}
                    {{ csrf_field() }}
                    {{ Form::hidden('id', $whatson->id) }}
                    <table class="table table-striped table-bordered table-hover table-sm datatable mdl-data-table dataTable" role="grid" style="width: 80%;">
							<tbody>
                            <tr>
                                <td>Title:</td>
                                <td>{{ Form::text('title', $whatson->title ,array('class' => 'form-control','placeholder' => 'Enter Event Title')) }}</td>
                            </tr>
                            <tr>
                                <td>Venue:</td>
                                <td>{{ Form::text('venue', $whatson->venue ,array('class' => 'form-control','placeholder' => 'Enter Event Venue')) }}</td>
                            </tr>
                            <tr>
                                <td>URL:</td>
                                <td>{{ Form::text('url', $whatson->url ,array('class' => 'form-control','placeholder' => 'Enter Event URL')) }}</td>
                            </tr>
                            <tr>
                                <td>Date From:</td>
                                <td>
                                  
                                        <div class='input-group date'>
                                            <input type='text' class="form-control"  name="date_from" id='datetimepicker_from' value="{{$whatson->date_from}}"/>
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                   
                                </td>
                            </tr>
                            <tr>
                                <td>Date To:</td>
                                <td>
                                   
                                        <div class='input-group date'>
                                            <input type='text' class="form-control"  name="date_to" id='datetimepicker_to' value="{{$whatson->date_to}}" />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                   
                                </td>
                            </tr>
                            <tr>
                                <td>Active (?):</td>
                                <td>{{Form::select('is_active', array( '' => '-----', 1 => 'Yes', 0 => 'No'), $whatson->is_active ,['class' => 'form-control'])}}</td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>       
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="btn-submit-container">
                    <button type="submit" class="btn btn-primary" placeholder="Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        &nbsp;
                        <a href="{{ route('whats-on.index') }}" title="Cancel" class="btn btn-primary btn cancel_Btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')
<script src="{{ asset('vendor/bootstrap-datetimepicker/moment.js') }}"></script>
<script src="{{ asset('vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js') }}"></script>
<script type="text/javascript">
		 $(document).ready(function(){
            $('#datetimepicker_from').datetimepicker({ format: 'LLL'});
            $('#datetimepicker_to').datetimepicker({ format: 'LLL'});
        });		

        $('#datetimepicker_from').datetimepicker({
            useCurrent: false, //this is important as the functions sets the default date value to the current value 
            format: 'YYYY-MM-DD h:mm:ss'
        });
       $('#datetimepicker_to').datetimepicker({
            useCurrent: false, //this is important as the functions sets the default date value to the current value 
            format: 'YYYY-MM-DD h:mm:ss'
        });
</script>
@endsection

resources/views/admin/whats-on/index.blade.php
@extends('adminlte::page')

@section('title', 'Filcaspro')

@section('content_header')
	<h1>Filcaspro<small> What's On Administration</small></h1>
@endsection

@section('css')
    <link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')
{{ csrf_field() }}
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					@include('layouts/error_box')
					
						<a href="{{ route('whats-on.create') }}" title="Add new Event" class="btn btn-primary btn-xs">
							<i class="glyphicon glyphicon-plus"></i> Add new Event
						</a>
						<br/><br/>
					
					<div class="table-responsive">
					<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
								<th>Title</th>
								<th>Venue</th>   
								<th>Date From</th>
								<th>Date To</th>
								<th>Active (?)</th>
                                <th></th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
					
					</div>
				</div>
			</div>
		</div>
@endsection

@section('js')
	
	<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
    <script src="{{ asset('js/helpers.js') }}"></script>
    <script src="{{ asset('js/ajax-interceptor.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {

			var dataTable = $('#dataTable').DataTable({
				processing: true,
				serverSide: true,
				deferRender: true,
				ajax: '{{ route("whats-on.index") }}',
				columnDefs: [
					{
						'targets': 0,
						'data': 'title',
						'name': 'title',
					},
					{
						'targets': 1,
						'data': 'venue',
						'name': 'venue',
					},
                    {
						'targets': 2,
						'data': 'date_from',
						'name': 'date_from',
					},
                    {
						'targets': 3,
						'data': 'date_to',
						'name': 'date_to',
					},
					{
						'targets': 4,
						'data': 'is_active',
						'name': 'is_active',
						mRender: function ( data, type, row ) {
							if(data == 0){
								return data = 'No';
							}else if(data == 1){
								return data = 'Yes';
							}else {
								//
							}
						}
					},
					{
						'targets': 5,
						'searchable': false,
						'sortable': false,
						'render': function (data, type, row) {
							return [
								'<a href="whats-on/' + row['id'] + '/edit" title="Edit" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i> Edit</a>' + " " +
								'<button data-id="' + row.id + '" type="button" title="Delete" class="btn btn-danger btn-xs delete-btn"><i class="fa fa-trash"></i> Delete</button>'
							];
						},
					},
				]
			});

			/**
			* Delete the record.
			*/
			$(document).on("click", ".delete-btn", function () {
				var self = this;
				var id = $(this).attr('data-id');
				var url = '{{ route('whats-on.destroy', ':id') }}'.replace(':id', id);
				console.log(url);
				console.log(id);
				
				dhtmlx.confirm({
					title:"Confirm Deletion",
					type:"confirm-warning",
					text:"Do you really want to delete this record?",
					callback: function (res) {

						if(!res) {
							return;
						}
				
						$.ajax({
							type: "DELETE",
							url: url,
							data: { _token: '{{csrf_token()}}' },
							success: function (response) {

								dhtmlx.alert({
									title: 'Record Deleted',
									text: 'The has been successfully deleted',
									callback: function () {
										dataTable.draw();
									}
								});

							},
							error: function (err) {
								
							}
						});
					}
				});
			});
		});
	</script>
@endsection