routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => 'web'], function () {

    Route::group([
        'prefix' => 'admin',
        //'middleware' => ['ability:s2s.*,view_module,true']
        //'middleware' => ['auth', 'admin']
    ], function () {
            Auth::routes();    
            
            Route::group([
                'prefix' => '',
                'middleware' => ['auth']
            ], function() {
                    Route::get('home', 'AdminController@home')->name('admin.home');
                    Route::resource('artists', 'ActorController', [
                        'parameters' => 'singular'
                    ]);

                    Route::resource('images', 'ImageController', [
                        'parameters' => 'singular',
                        'except' => ['index','edit','store','update','create'],
                    ]);

                    Route::resource('contact', 'ContactController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                    Route::resource('register', 'RegisterController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                    Route::get('archived', 'WhatsUpController@archived')->name('whats-up.archived');
                    Route::resource('whats-up', 'WhatsUpController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('inquiry', 'InquiryController', [
                        'parameters' => 'singular',
                        'except' => ['show','edit','store','update','create','destroy'],
                    ]);

                   Route::resource('video', 'VideoController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('whats-on', 'WhatsOnController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('skill', 'SkillController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('creatives', 'CreativeController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::get('whats-in/{whats_in}/tags', 'WhatsInController@tags')->name('whats-in.tags');
                    Route::resource('whats-in', 'WhatsInController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('category', 'CategoryController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);

                    Route::resource('writer', 'WriterController', [
                        'parameters' => 'singular',
                        'except' => ['show'],
                    ]);
                } 
            );
        }
    );

    Route::group([
        'prefix'     => '',
    ], function() {

        Route::get('', 'WebsiteController@index')->name('web.index');
        Route::get('index', 'WebsiteController@index')->name('web.index');
        Route::get('home', 'WebsiteController@home')->name('web.home');
        
        Route::post('artist/search', 'WebActorController@search')->name('web.artist.search');
        Route::resource('artist', 'WebActorController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.artist.index',
                'show' => 'web.artist.show',
            ]
        ]);
       
       
        Route::post('creative/search', 'WebCreativeController@search')->name('web.creative.search');
        Route::resource('creative', 'WebCreativeController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.creative.index',
                'show' => 'web.creative.show',
            ]
        ]);
    
        Route::get('whats-up/disclaimer', 'WebWhatsUpController@disclaimer')->name('web.whats-up.disclaimer');
        Route::resource('whats-up', 'WebWhatsUpController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-up.index',
                'show' => 'web.whats-up.show',
            ]
        ]);

        Route::resource('whats-on', 'WebWhatsOnController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-on.index',
                'show' => 'web.whats-on.show',
            ]
        ]);

        Route::post('whats-in/search', 'WebWhatsInController@search')->name('web.whats-in.search');
        Route::resource('whats-in', 'WebWhatsInController', [
            'parameters' => 'singular',
            'except' => ['edit','store','update','create','destroy'],
            'names' => [
                'index' => 'web.whats-in.index',
                'show' => 'web.whats-in.show',
            ]
        ]);

        Route::resource('contact', 'WebContactController', [
            'parameters' => 'singular',
            'except' => ['edit','show','update','create','destroy'],
            'names' => [
                'index' => 'web.contact.index',
                'store' => 'web.contact.store',
            ]
        ]);
        
        Route::resource('register', 'WebRegisterController', [
            'parameters' => 'singular',
            'except' => ['edit','show','update','create','destroy'],
            'names' => [
                'index' => 'web.register.index',
                'store' => 'web.register.store',
            ]
            
        ]);

        Route::post('actor-inquire','WebsiteController@actorInquire')->name('web.actor-inquire');
        Route::post('creative-inquire','WebsiteController@creativeInquire')->name('web.creative-inquire');
    });
    
});

app/Writer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Writer extends Model
{
    public function WhatsUp(){
        return $this->hasMany('App\WhatsUp');
    }
}

app/Http/Controllers/WriterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Writer;
use Yajra\Datatables\Datatables;
use Carbon\Carbon;

class WriterController extends Controller
{
    /*
    * display listing of the resource
    *
    *
    */
    public function index(Request $request)
	{
		if ($request->ajax()) {
            $writers = Writer::all();
			return Datatables::of($writers)->make(true);
        }

		return view('admin.writer.index');
    }

    /*
    *  open the form to edit the specified resource
    *
    *
    */
    public function edit($id){
        $writer = Writer::find($id);
        return view('admin.writer.edit', compact('writer') );
        // return $whatsup;
    }

    /*
    *  Update the specified resource
    *
    *
    */
    public function update(Request $request){

        $id = $request->input('id');
        
		$this->validate($request, [
            'name' => 'required',
            'title' => 'required'

        ]);
        
        if($request->hasFile('image')){

            $path = 'public/images/writers/';
            $image = $request->file('image');
            $photoname = md5_file($image->getRealPath() );
            $ext = $image->guessExtension();
            $file = $image->storeAs($path, $photoname.'.'.$ext);
    
            $data = [
                'name' => $request->input('name'),
                'title' => $request->input('title'),
                'image' => $photoname.'.'.$ext,
                'created_at' => Carbon::now()
            ];

        }else {
            $data = [
                'name' => $request->input('name'),
                'title' => $request->input('title'),
                'created_at' => Carbon::now()
            ];
        }
       
        
        Writer::where('id', '=', $id)->update($data);
	
		return redirect()->route('writer.index');
    }

    /*
    *  open the form to create new resource
    *
    *
    */
    public function create(){
        return view('admin.writer.create');
    }

    /*
    *  store the newly created resource
    *
    *
    */
    public function store(Request $request){
       
        $this->validate($request, [
            'name' => 'required',
            'title' => 'required'

        ]);
        
        $path = 'public/images/writers/';
        $image = $request->file('image');
        $photoname = md5_file($image->getRealPath() );
        $ext = $image->guessExtension();
        $file = $image->storeAs($path, $photoname.'.'.$ext);
 
        $data = [
            'name' => $request->input('name'),
            'title' => $request->input('title'),
            'image' => $photoname.'.'.$ext,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ];

        Writer::insert($data);
	
		return redirect()->route('writer.index');
    }

    /*
    *  delete the selected resource
    *
    *
    */
    public function destroy($id){
        WhatsUp::where('id','=', $id)->delete();
        return response()->json([
            "success" => "true",
            "message" => "Record has been deleted.",
        ]);
    }
}

resources/views/admin/writer/create.blade.php
@extends('adminlte::page')

@section('title', 'Filcaspro')

@section('content_header')
	<h1>Filcaspro<small> Create Writer</small></h1>
@endsection

@section('css')
<!-- Froala Editor -->        
	
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_editor.min.css')}}">
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_style.min.css')}}">

  <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

  <link href="{{ asset('css/billboard.css') }}" rel="stylesheet">
@endsection

@section('content')
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-md-12">
                   
                    @include('layouts/error_box')
                    {{Form::open(array('route' => array('writer.store'), 'method' => 'POST', 'class' =>'form-horizontal', 'files' => true))}}
                    {{ csrf_field() }}
                    <table class="table table-striped table-bordered table-hover table-sm datatable mdl-data-table dataTable" role="grid" style="width: 80%;">
						<tbody>
                            <tr>
                                <td>Name:</td>
                                <td>{{Form::text('name', null , array('class' => 'form-control','placeholder' => 'Enter Writer Name')) }}</td>
                            </tr>
                            <tr>
                                <td>Title:</td>
                                <td>{{ Form::text('title', null , array('class' => 'form-control','placeholder' => 'Enter Writer Title')) }}</td>
                            </tr>
                            <tr>
                                <td>Image:</td>
                                <td> {{ Form::file('image') }}</td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>       
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="btn-submit-container">
                    <button type="submit" class="btn btn-primary" placeholder="Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        &nbsp;
                        <a href="{{ route('writer.index') }}" title="Cancel" class="btn btn-primary btn cancel_Btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')

<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
<script src="{{ asset('js/helpers.js') }}"></script>
<script src="{{ asset('js/ajax-interceptor.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/froala/js/froala_editor.min.js')}}"></script>
<script type="text/javascript">
				
    $(function() {
        $('textarea#froala-editor').froalaEditor({
            iframe: true,
        })
    });
  
</script>
@endsection

resources/views/admin/writer/edit.blade.php
@extends('adminlte::page')

@section('title', 'Filcaspro')

@section('content_header')
	<h1>Filcaspro<small> Edit Writer</small></h1>
@endsection

@section('css')
<!-- Froala Editor -->        
	
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_editor.min.css')}}">
  <link rel="stylesheet" href="{{ asset('vendor/froala/css/froala_style.min.css')}}">

  <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

  <link href="{{ asset('css/billboard.css') }}" rel="stylesheet">
@endsection

@section('content')
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-md-12">
                 
                    @include('layouts/error_box') 
                    {{Form::open(array('route' => array('writer.update', $writer->id), 'method' => 'PUT', 'class' =>'form-horizontal', 'files' => true))}}
                    {{ csrf_field() }}
                    {{ Form::hidden('id', $writer->id) }} 
                    <table class="table table-striped table-bordered table-hover table-sm datatable mdl-data-table dataTable" role="grid" style="width: 80%;">
                        <tbody>
                            <tr>
                                <td>Name:</td>
                                <td>{{Form::text('name', $writer->name , array('class' => 'form-control','placeholder' => 'Enter Writer Name')) }}</td>
                            </tr>
                            <tr>
                                <td>Title:</td>
                                <td>{{ Form::text('title', $writer->title , array('class' => 'form-control','placeholder' => 'Enter Writer Title')) }}</td>
                            </tr>
                            <tr>
                                <td>Image:</td>
                                <td> {{ Form::file('image') }}</td>
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>       
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="btn-submit-container">
                    <button type="submit" class="btn btn-primary" placeholder="Submit"><i class="glyphicon glyphicon-check"></i> Save</button>
                        &nbsp;
                        <a href="{{ route('writer.index') }}" title="Cancel" class="btn btn-primary btn cancel_Btn">
                            <i class="glyphicon glyphicon-remove-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')

<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
<script src="{{ asset('js/helpers.js') }}"></script>
<script src="{{ asset('js/ajax-interceptor.js') }}"></script>
<script type='text/javascript' src="{{ asset('vendor/froala/js/froala_editor.min.js')}}"></script>
<script type="text/javascript">
				
    $(function() {
        $('textarea#froala-editor').froalaEditor({
            iframe: true,
        })
    });
  
</script>
@endsection

resources/views/admin/writer/index.blade.php
@extends('adminlte::page')

@section('title', 'Filcaspro')

@section('content_header')
	<h1>Filcaspro<small> What's Up Administration</small></h1>
@endsection

@section('css')
    <link rel="stylesheet"
          href="{{ asset('css/app.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.css') }}">

    <link rel="stylesheet"
          href="{{ asset('vendor/dhtmlxSuite/codebase/fonts/font_roboto/roboto.css') }}">

@endsection

@section('content')
{{ csrf_field() }}
	<div class="box box-default">
		<div class="box-body">
			<div class="row">
				<div class="col-xs-12">
					@include('layouts/error_box')
					
						<a href="{{ route('writer.create') }}" title="Add new Writer" class="btn btn-primary btn-xs">
							<i class="glyphicon glyphicon-plus"></i> Add new Writer
						</a>
						<br/><br/>
					
					<div class="table-responsive">
					<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
								<th>Name</th>
								<th>Title</th>
                                <th></th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
					
					</div>
				</div>
			</div>
		</div>
@endsection

@section('js')
	
	<script src="{{ asset('vendor/dhtmlxSuite/codebase/dhtmlx.js') }}"></script>
    <script src="{{ asset('js/helpers.js') }}"></script>
    <script src="{{ asset('js/ajax-interceptor.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() {

			var dataTable = $('#dataTable').DataTable({
				processing: true,
				serverSide: true,
				deferRender: true,
				ajax: '{{ route("writer.index") }}',
				columnDefs: [
					{
						'targets': 0,
						'data': 'name',
						'name': 'name',
					},
					{
						'targets': 1,
						'data': 'title',
						'name': 'title',
					},
					{
						'targets': 2,
						'searchable': false,
						'sortable': false,
						'render': function (data, type, row) {
							return [
								'<a href="writer/' + row['id'] + '/edit" title="Edit" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-edit"></i> Edit</a>' + " " +
								'<button data-id="' + row.id + '" type="button" title="Delete" class="btn btn-danger btn-xs delete-btn"><i class="fa fa-trash"></i> Delete</button>'
							];
						},
					},
				]
			});

			/**
			* Delete the record.
			*/
			$(document).on("click", ".delete-btn", function () {
				var self = this;
				var id = $(this).attr('data-id');
				var url = '{{ route('writer.destroy', ':id') }}'.replace(':id', id);
				console.log(url);
				console.log(id);
				
				dhtmlx.confirm({
					title:"Confirm Deletion",
					type:"confirm-warning",
					text:"Do you really want to delete this record?",
					callback: function (res) {

						if(!res) {
							return;
						}
				
						$.ajax({
							type: "DELETE",
							url: url,
							data: { _token: '{{csrf_token()}}' },
							success: function (response) {

								dhtmlx.alert({
									title: 'Record Deleted',
									text: 'The has been successfully deleted',
									callback: function () {
										dataTable.draw();
									}
								});

							},
							error: function (err) {
								
							}
						});
					}
				});
			});
		});
	</script>
@endsection